### ISSUE TITLE
Atom refuses to create a worker

### ISSUE THREAD

**Issue by Holger-Will** [apla/atom-jscad#12]
I get the following error when trying to render a preview:

> Uncaught DOMException: Failed to construct 'Worker': Access to the script at 'blob:file:///4d8122a1-4c76-4188-8671-774ba8975a55' is denied by the document's Content Security Policy.
>     at Function.OpenJsCad.parseJsCadScriptASync [as __old] (file:///home/holger/.atom/packages/atom-jscad/standalone/openjscad.js:259:16)
>     at Function.parseJsCadScriptASync (/home/holger/.atom/packages/atom-jscad/standalone/overrides.js:86:34)
>     at OpenJsCad.Processor.rebuildSolid (file:///home/holger/.atom/packages/atom-jscad/standalone/openjscad.js:857:33)
>     at OpenJsCad.Processor.setJsCad (file:///home/holger/.atom/packages/atom-jscad/standalone/openjscad.js:777:12)
>     at AtomScadPreviewView.module.exports.AtomScadPreviewView.render (/home/holger/.atom/packages/atom-jscad/lib/atom-scad-preview-view.js:147:20)
>     at AtomScadPreviewView.dependencyLoaded (/home/holger/.atom/packages/atom-jscad/lib/atom-scad-preview-view.js:216:14)

**Comment by TimothyJSON** [comment]
Same. Any suggestions or is this already closed?

**Comment by cerdoc** [comment]
Hello.
Same problem.

**Comment by WolfgangFahl** [comment]
same issue

**Comment by apla** [comment]
Unfortunately, new Atom break some APIs to allow Blob CSP. At first, schema changed from `blob:` to `blob:file://`, then (they deprecated)[https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md] methods, which allows me to bypass security restrictions.

So, now it should be implemented as [protocol](https://github.com/electron/electron/blob/879462af4b421f3c6a64b52605e5d3d16fc4c19d/docs/api/protocol.md)

I don't have time for those games.
