### ISSUE TITLE
Failed to load the atom-jscad package

### ISSUE THREAD

**Issue by RHPrice2** [apla/atom-jscad#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [atom-jscad](https://github.com/apla/atom-jscad) package 1.2.1

### Stack Trace

Failed to load the atom-jscad package

```
At webFrame.registerURLSchemeAsBypassingCSP is not a function

TypeError: webFrame.registerURLSchemeAsBypassingCSP is not a function
    at /packages/atom-jscad/lib/atom-scad-preview-view.js:28:10)
    at /packages/atom-jscad/lib/atom-scad-preview-view.js:295:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/atom-jscad/lib/atom-scad-preview.js:16:27)
    at /packages/atom-jscad/lib/atom-scad-preview.js:304:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3204187)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3190727
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3189559)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3190300)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381522)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379945
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332010)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379883)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:716025
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718064)
```

### Commands

```
```

### Non-Core Packages

```
atom-jscad 1.2.1 
```

**Comment by RHPrice2** [comment]
Something in my configuration is not quite right and I could use a pointer.  Seems like this is an unsupported program... and it is a shame because I an looking forward to jscad on Atom.

**Comment by JWD-Vektor** [comment]
Did you ever get the install resolved? I have same problem.

**Comment by RHPrice2** [comment]
No,  and I invested time more time in this than I had trying to get this to work.  At the end of the day, I still needed to complete a build.  I reverted to OpenScad and built my 3d prints that way.  I have used OpenScad before and I know the program.

I am still interested.  I am a light programer and OpenScad does not have the variable structure that I am accustomed to.  I do not get into the myriad of utility programs to build a set of scripts into another program.   Unless there has been some real progress in developing an installable version for the Mac, I am not inclined to invest more time trying to solve the same problems a second / third time.  

You tell me, Have you made any progress getting your version of OpenJScad up an running for the masses?


Roby Price
rhprice2@Mac.com

**Comment by JWD-Vektor** [comment]
Thanks, so much for the reply.

I was actually more interested in maker.js but could not get that to work either.

I just gave up on both of them.

I’m retired and am sitting on thousands of lines of Application code I hacked in AlphaCAM over the years.

I’ve gone from retired to extremely tired :)

I don’t give up easy but I think I have had it.

 

Stay safe and prosper!

 

JD

**Comment by apla** [comment]
One day Atom authors changed html security and now it's not possible to use atom-jscad. 

Digging deeper, seems CSP now not allowing to create `blob:` with Function object. So, only possible way to launch it is by modifying Atom itself. What a waste of my time… Fuck Atom, then.

If I choose to touch this project again, it will support VS Code, because everyone now using VS Code and Atom is dead.

**Comment by tuggerfub** [comment]
Man, this is disappointing.
